#!/bin/sh
set -e

# expose environment since 5.3 does not support clear_env = no
PHP_ENV="/usr/local/etc/php-fpm.d/env.conf"
echo "[www]" > "$PHP_ENV"
env | while IFS='=' read -r name value ; do
	if [ ! -z "$name" -a ! -z "$value" ] ; then
		echo "env[$name] = '$value'" >> "$PHP_ENV"
	fi
done

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

USER="www-data"
if [ ! -z "$USER_ID" -a ! -z "$GROUP_ID" ] ; then
   echo "Switching to user"
   USER="user"
   deluser "$USER"
   delgroup "$USER"
   addgroup --gid "$GROUP_ID" "$USER"
   adduser --disabled-password --disabled-login --no-create-home --system --uid "$USER_ID" --gid "$GROUP_ID" "$USER"
fi
sed -e "s/%%USER%%/$USER/" "/usr/local/etc/php-fpm.d/zz-docker.conf.tpl" > /usr/local/etc/php-fpm.d/zz-docker.conf

exec "$@"
